Add Account Endpoint and Logic
Leagueify/api pull request #9
Opened 2024-04-16 22:21 UTC by MichaelCduBois

This is a work in progress. Items I need to complete:
- [ ] `accounts` Sends email if existing configuration
- [ ] `accounts/:id/verify` logic
- [ ] `accounts/:id/verify` returns JWT if successful

2024-04-18 03:43 UTC, kylekrny requested changes

2024-04-18 03:43 UTC, kylekrny commented on README.md
> +make init
When I attempt to run make init I get the error:
```
go get .
make: go: No such file or directory
make: *** [init] Error 1
```

2024-04-18 03:45 UTC, MichaelCduBois commented on README.md
> +make init
Might be a dumb question...is Go installed?

2024-04-18 06:27 UTC, kylekrny commented
@MichaelCduBois If I hit server.localhost I should get a response right? API docs should be there?

2024-04-18 13:02 UTC, MichaelCduBois commented
> @MichaelCduBois If I hit server.localhost I should get a response right? API docs should be there?

server.localhost/api

I'll update the README.

2024-04-19 03:57 UTC, kylekrny approved these changes

2024-04-19 03:57 UTC, merged